--Chronicle Maintenance Utility
--by wyykak

c13959997={}
Duel.LoadScript("c13959997.lua")
local tpu=c13959997

c13959970={}
Duel.LoadScript("c13959970.lua")
local cnu=c13959970

local cc=13959971
local this=_G["c"..cc]

this.dlCode=13959972

function this.initial_effect(c)
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_QUICK_O)
	e1:SetCode(EVENT_FREE_CHAIN)
	e1:SetProperty(EFFECT_FLAG_IGNORE_IMMUNE|EFFECT_FLAG_SET_AVAILABLE|EFFECT_FLAG_CANNOT_DISABLE|EFFECT_FLAG_CANNOT_INACTIVATE|EFFECT_FLAG_CANNOT_NEGATE|EFFECT_FLAG_DAMAGE_STEP|EFFECT_FLAG_DAMAGE_CAL|EFFECT_FLAG_UNCOPYABLE)
	e1:SetRange(LOCATION_DECK|LOCATION_HAND|LOCATION_MZONE|LOCATION_SZONE|LOCATION_GRAVE|LOCATION_REMOVED)
	e1:SetOperation(this.op1)
	c:RegisterEffect(e1)
end

function this.op1(e,tp)
	local dl=cnu.loadDeckList(this.dlCode)
	Debug.Message("已从c"..this.dlCode..".lua加载卡组表")
	Debug.Message("卡组数量:"..#dl)
	Debug.Message("开始从chronicle/decks目录读取卡组……")
	local deckList={}
	local strict=Duel.SelectYesNo(tp,aux.Stringid(cc,0))
	for l in io.lines("chronicle/index.txt") do
		if l:sub(1,1)~="#" then
			local deck=cnu.loadDeck("chronicle/decks/"..l,strict)
			if not deck then
				Debug.Message(l.."读取失败，跳过")
			else
				local cardList={}
				local numList=""
				for tcc,_ in pairs(deck) do
					cardList[#cardList+1]=tcc
				end
				cardList=tpu.toList(tpu.toSet(cardList))
				for _,tcc in pairs(cardList) do
					numList=numList..tostring(deck[tcc])
				end
				deckList[#deckList+1]=tpu.dumpSet(tpu.toSet(cardList))
				deckList[#deckList+1]=numList
			end
		end
	end
	Debug.Message("读取完成，共"..#deckList//2 .."个卡组")
	Debug.Message("开始写入卡组表文件……")
	local f=io.open("chronicle/c"..this.dlCode..".lua","w")
	f:write(this.template:format(cc,this.dlCode))
	for _,s in pairs(deckList) do
		f:write("\""..s.."\",\n")
	end
	f:write("}\n")
	f:flush()
	f:close()
end

this.template="--Chronicle Deck List\n--Generated by %d\nlocal cc=%d\nlocal this=_G[\"c\"..cc]\nthis.deckList={\n"

